spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    driver-class-name: org.h2.Driver
#    username: sa

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://user.clkxahvngcma.ap-northeast-2.rds.amazonaws.com:3306/todaytodo
    username: user
    password: vf-lDunOvx1D02cr1lJ5WS3XE

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
    prefix:
      classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  main:
    allow-bean-definition-overriding: true

server:
  address: 3.38.81.31
  port: 8080